# Generated by Django 4.1.1 on 2022-12-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_images',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_model',
        ),
        migrations.AddField(
            model_name='car',
            name='images',
            field=models.TextField(default='BMW'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.TextField(default='2022'),
        ),
    ]
