# Generated by Django 4.1.1 on 2022-12-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_rename_title_car_name_remove_car_car_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='images',
            field=models.CharField(default='BMW', max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(default='2022', max_length=255),
        ),
    ]
