# Generated by Django 4.1.1 on 2022-12-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='images',
            field=models.TextField(default='BMW'),
        ),
    ]
