# Generated by Django 4.1.1 on 2022-12-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_car_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='images',
            field=models.TextField(default='Add car image'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(default='Add car model ', max_length=255),
        ),
    ]
